version: '3.8'
services:
  dotnet_main:
    image: dotnet_main
    container_name: dotnet_main
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - "7000:80"
    environment:
      ConnectionStrings__Default : Server=dotnet_postgres;Port=5432;Database=DefaultDB;User Id=admin;Password=admin1234
      RabbitMQSettings__Username: admin
      RabbitMQSettings__Password: admin1234
      RabbitMQSettings__Hostname: dotnet_rabbitmq
      RabbitMQSettings__Port: 5672
      MongoDBConfig__ConnectionString : mongodb://admin:admin1234@dotnet_mongodb:27017
      MongoDBCOnfig__DatabaseName : OrderDB
      MongoDBConfig__CollectionName : Orders
      OpenTelemetryConfig__OtlpExporterEndpoint : http://dotnet_jaeger:4317
    depends_on: 
      - dotnet_postgres
      - dotnet_rabbitmq
      - dotnet_mongodb
      - dotnet_jaeger

  dotnet_postgres:
    image: postgres:alpine
    container_name: dotnet_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER : admin
      POSTGRES_PASSWORD : admin1234
      POSTGRES_DB : DefaultDB

  dotnet_mailing:
    image: dotnet_mailing
    container_name: dotnet_mailing
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    ports:
      - "7001:80"
    environment:
      EmailConfig__Email : testuser147000@gmail.com
      EmailConfig__Host : smtp.gmail.com
      EmailConfig__Port : 25
      EmailConfig__Password : bepbttnaukmejrpw
      RabbitMQSettings__Username : admin
      RabbitMQSettings__Password : admin1234
      RabbitMQSettings__Hostname : dotnet_rabbitmq
      RabbitMQSettings__Port: 5672
    depends_on: 
      - dotnet_rabbitmq
  
  dotnet_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dotnet_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER : admin
      RABBITMQ_DEFAULT_PASS : admin1234

  dotnet_storage:
    image: dotnet_storage
    container_name: dotnet_storage
    build:
      context: .
      dockerfile: Dotnet.Homeworks.Storage.API/Dockerfile
    ports:
      - "7002:80"
    environment:
      MinioConfig__Username : admin
      MinioConfig__Password : admin1234
      MinioConfig__Endpoint : dotnet-minio
      MinioConfig__Port : 9000
      MinioConfig__WithSsl : false
    depends_on:
      - dotnet_minio

  dotnet_minio:
    image: minio/minio:latest
    container_name: dotnet-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER : admin
      MINIO_ROOT_PASSWORD : admin1234
    command: server --console-address ":9001" /data/
        
  dotnet_mongodb:
    image: mongo:latest
    container_name: dotnet_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME : admin
      MONGO_INITDB_ROOT_PASSWORD : admin1234
      
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: dotnet_jaeger
    ports:
      - "14268:14268"
      - "16686:16686"
    environment:
      COLLECTOR_OTLP_ENABLED : true